"""
Django settings for cinebooks project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Em produção, defina a variável de ambiente DJANGO_SECRET_KEY com um valor
# só seu. Localmente, se ela não existir, usamos a chave abaixo (só para
# desenvolvimento, sem problema).
SECRET_KEY = os.environ.get(
    "DJANGO_SECRET_KEY",
    "django-insecure-^#4-t0te+2@u4t=!58%n3!gys8we+%)w(gtx1fz=6!6fyfc_=3",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Localmente fica True (mostra erros detalhados). No servidor de produção,
# defina a variável de ambiente DJANGO_DEBUG=False.
DEBUG = os.environ.get("DJANGO_DEBUG", "True") == "True"

# Em produção, defina a variável de ambiente DJANGO_ALLOWED_HOSTS com os
# domínios separados por vírgula, ex: "seuusuario.pythonanywhere.com"
_hosts_env = os.environ.get("DJANGO_ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in _hosts_env.split(",") if h.strip()]

# Chave gratuita da API do TMDB (themoviedb.org), usada para buscar
# automaticamente os pôsteres de filmes e séries. Veja o README para saber
# como criar a sua. Sem essa variável definida, a busca de capas de
# filmes/séries simplesmente não roda (livros continuam funcionando, pois
# usam o Open Library, que não precisa de chave).
TMDB_API_KEY = os.environ.get("TMDB_API_KEY", "")

# Chave gratuita da API do OMDb (omdbapi.com), usada para buscar a nota do
# público (IMDb) e a nota da crítica (Metacritic) de filmes e séries. Crie a
# sua de graça em http://www.omdbapi.com/apikey.aspx (chega por e-mail em
# poucos minutos). Sem essa variável definida, o site simplesmente não mostra
# essas notas externas — nada quebra.
OMDB_API_KEY = os.environ.get("OMDB_API_KEY", "")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "catalog",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Whitenoise serve os arquivos estáticos (CSS) direto pela própria
    # aplicação Django em produção — necessário no Render, que (diferente do
    # PythonAnywhere) não tem um jeito próprio de servir estáticos.
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cinebooks.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cinebooks.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Localmente usamos SQLite (arquivo db.sqlite3, sem configuração nenhuma).
# Em produção (Render), a variável de ambiente DATABASE_URL é criada
# automaticamente quando você conecta um banco Postgres, e usamos ela.
DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [BASE_DIR / "static"]
# Pasta onde `python manage.py collectstatic` vai juntar todos os arquivos
# estáticos para servir em produção.
STATIC_ROOT = BASE_DIR / "staticfiles"
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

LOGIN_URL = "login"
LOGIN_REDIRECT_URL = "home"
LOGOUT_REDIRECT_URL = "home"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
