# Generated by Django 5.2.17 on 2026-08-13 17:41

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Genero",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=50, unique=True, verbose_name="nome"),
                ),
            ],
            options={
                "verbose_name": "gênero",
                "verbose_name_plural": "gêneros",
                "ordering": ["nome"],
            },
        ),
        migrations.CreateModel(
            name="Filme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("sinopse", models.TextField(blank=True, verbose_name="sinopse")),
                (
                    "ano_lancamento",
                    models.PositiveIntegerField(verbose_name="ano de lançamento"),
                ),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        help_text="Link de uma imagem (opcional). Se deixar em branco, usamos uma imagem padrão.",
                        verbose_name="URL do pôster/capa",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="adicionado em"
                    ),
                ),
                (
                    "diretor",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="diretor(a)"
                    ),
                ),
                (
                    "duracao_minutos",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="duração (minutos)"
                    ),
                ),
                (
                    "generos",
                    models.ManyToManyField(
                        blank=True, to="catalog.genero", verbose_name="gêneros"
                    ),
                ),
            ],
            options={
                "verbose_name": "filme",
                "verbose_name_plural": "filmes",
                "ordering": ["-ano_lancamento", "titulo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("sinopse", models.TextField(blank=True, verbose_name="sinopse")),
                (
                    "ano_lancamento",
                    models.PositiveIntegerField(verbose_name="ano de lançamento"),
                ),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        help_text="Link de uma imagem (opcional). Se deixar em branco, usamos uma imagem padrão.",
                        verbose_name="URL do pôster/capa",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="adicionado em"
                    ),
                ),
                (
                    "autor",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="autor(a)"
                    ),
                ),
                (
                    "editora",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="editora"
                    ),
                ),
                (
                    "numero_paginas",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número de páginas"
                    ),
                ),
                (
                    "generos",
                    models.ManyToManyField(
                        blank=True, to="catalog.genero", verbose_name="gêneros"
                    ),
                ),
            ],
            options={
                "verbose_name": "livro",
                "verbose_name_plural": "livros",
                "ordering": ["-ano_lancamento", "titulo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Serie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="título")),
                ("sinopse", models.TextField(blank=True, verbose_name="sinopse")),
                (
                    "ano_lancamento",
                    models.PositiveIntegerField(verbose_name="ano de lançamento"),
                ),
                (
                    "poster_url",
                    models.URLField(
                        blank=True,
                        help_text="Link de uma imagem (opcional). Se deixar em branco, usamos uma imagem padrão.",
                        verbose_name="URL do pôster/capa",
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="adicionado em"
                    ),
                ),
                (
                    "criador",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="criador(a)"
                    ),
                ),
                (
                    "numero_temporadas",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="número de temporadas"
                    ),
                ),
                (
                    "generos",
                    models.ManyToManyField(
                        blank=True, to="catalog.genero", verbose_name="gêneros"
                    ),
                ),
            ],
            options={
                "verbose_name": "série",
                "verbose_name_plural": "séries",
                "ordering": ["-ano_lancamento", "titulo"],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Avaliacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="nota",
                    ),
                ),
                ("comentario", models.TextField(blank=True, verbose_name="comentário")),
                (
                    "criado_em",
                    models.DateTimeField(auto_now_add=True, verbose_name="criado em"),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "avaliação",
                "verbose_name_plural": "avaliações",
                "ordering": ["-criado_em"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "content_type", "object_id"),
                        name="usuario_avalia_uma_vez_cada_titulo",
                    )
                ],
            },
        ),
    ]
