# Generated by Django 5.2.17 on 2026-08-13 22:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=150, unique=True, verbose_name="nome"),
                ),
                ("foto_url", models.URLField(blank=True, verbose_name="URL da foto")),
            ],
            options={
                "verbose_name": "pessoa",
                "verbose_name_plural": "pessoas",
                "ordering": ["nome"],
            },
        ),
        migrations.AddField(
            model_name="filme",
            name="dados_completos",
            field=models.BooleanField(default=False, verbose_name="dados completos"),
        ),
        migrations.AddField(
            model_name="filme",
            name="id_externo",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="ID na API externa"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="dados_completos",
            field=models.BooleanField(default=False, verbose_name="dados completos"),
        ),
        migrations.AddField(
            model_name="livro",
            name="id_externo",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="ID na API externa"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="dados_completos",
            field=models.BooleanField(default=False, verbose_name="dados completos"),
        ),
        migrations.AddField(
            model_name="serie",
            name="id_externo",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="ID na API externa"
            ),
        ),
        migrations.AddField(
            model_name="filme",
            name="elenco",
            field=models.ManyToManyField(
                blank=True,
                related_name="filmes",
                to="catalog.pessoa",
                verbose_name="elenco",
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="autor_pessoa",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="livros",
                to="catalog.pessoa",
                verbose_name="autor(a) (com foto)",
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="elenco",
            field=models.ManyToManyField(
                blank=True,
                related_name="series",
                to="catalog.pessoa",
                verbose_name="elenco",
            ),
        ),
    ]
