# Generated by Django 5.2.17 on 2026-08-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_pessoa_filme_dados_completos_filme_id_externo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="nota_critica",
            field=models.FloatField(
                blank=True, null=True, verbose_name="nota da crítica (internet)"
            ),
        ),
        migrations.AddField(
            model_name="filme",
            name="nota_publico",
            field=models.FloatField(
                blank=True, null=True, verbose_name="nota do público (internet)"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="nota_critica",
            field=models.FloatField(
                blank=True, null=True, verbose_name="nota da crítica (internet)"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="nota_publico",
            field=models.FloatField(
                blank=True, null=True, verbose_name="nota do público (internet)"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="nota_critica",
            field=models.FloatField(
                blank=True, null=True, verbose_name="nota da crítica (internet)"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="nota_publico",
            field=models.FloatField(
                blank=True, null=True, verbose_name="nota do público (internet)"
            ),
        ),
    ]
