# Generated by Django 5.2.17 on 2026-08-13 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_perfilusuario"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PerfilUsuario",
        ),
    ]
