# Generated by Django 5.2.17 on 2026-08-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_delete_perfilusuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="imdb_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="ID no IMDb"
            ),
        ),
        migrations.AddField(
            model_name="filme",
            name="nota_rotten_tomatoes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="nota Rotten Tomatoes (%)"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="imdb_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="ID no IMDb"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="nota_rotten_tomatoes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="nota Rotten Tomatoes (%)"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="imdb_id",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="ID no IMDb"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="nota_rotten_tomatoes",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="nota Rotten Tomatoes (%)"
            ),
        ),
    ]
