# Generated by Django 5.2.17 on 2026-08-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_filme_imdb_id_filme_nota_rotten_tomatoes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="notas_omdb_verificadas",
            field=models.BooleanField(
                default=False, verbose_name="notas do OMDb já verificadas"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="notas_omdb_verificadas",
            field=models.BooleanField(
                default=False, verbose_name="notas do OMDb já verificadas"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="notas_omdb_verificadas",
            field=models.BooleanField(
                default=False, verbose_name="notas do OMDb já verificadas"
            ),
        ),
    ]
