# Generated by Django 5.2.17 on 2026-08-17 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_filme_notas_omdb_verificadas_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="idioma_tmdb_conteudo",
            field=models.CharField(
                blank=True,
                default="pt-BR",
                max_length=10,
                verbose_name="idioma do conteúdo cadastrado",
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="idioma_tmdb_conteudo",
            field=models.CharField(
                blank=True,
                default="pt-BR",
                max_length=10,
                verbose_name="idioma do conteúdo cadastrado",
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="idioma_tmdb_conteudo",
            field=models.CharField(
                blank=True,
                default="pt-BR",
                max_length=10,
                verbose_name="idioma do conteúdo cadastrado",
            ),
        ),
    ]
