# Generated by Django 5.2.17 on 2026-08-17 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_filme_idioma_tmdb_conteudo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="traducoes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="traduções para exibição"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="traducoes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="traduções para exibição"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="traducoes",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="traduções para exibição"
            ),
        ),
    ]
