# Generated by Django 5.2.17 on 2026-08-18 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_querover"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="data_lancamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="data de lançamento"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="data_lancamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="data de lançamento"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="data_lancamento",
            field=models.DateField(
                blank=True, null=True, verbose_name="data de lançamento"
            ),
        ),
    ]
