# Generated by Django 5.2.17 on 2026-08-18 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_filme_data_lancamento_livro_data_lancamento_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="onde_assistir",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="onde assistir"
            ),
        ),
        migrations.AddField(
            model_name="livro",
            name="onde_assistir",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="onde assistir"
            ),
        ),
        migrations.AddField(
            model_name="serie",
            name="onde_assistir",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="onde assistir"
            ),
        ),
    ]
