# Generated by Django 5.2.17 on 2026-08-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_filme_onde_assistir_livro_onde_assistir_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="filme",
            name="trailer_youtube_url",
            field=models.URLField(blank=True, verbose_name="trailer no YouTube"),
        ),
        migrations.AddField(
            model_name="livro",
            name="trailer_youtube_url",
            field=models.URLField(blank=True, verbose_name="trailer no YouTube"),
        ),
        migrations.AddField(
            model_name="serie",
            name="trailer_youtube_url",
            field=models.URLField(blank=True, verbose_name="trailer no YouTube"),
        ),
    ]
