# Generated by Django 5.2.17 on 2026-08-21 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_busca"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Adaptacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "pontuacao_similaridade",
                    models.FloatField(
                        default=0.0, verbose_name="pontuação de similaridade do título"
                    ),
                ),
                (
                    "criado_em",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="detectado em"
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "livro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adaptacoes",
                        to="catalog.livro",
                        verbose_name="livro",
                    ),
                ),
            ],
            options={
                "verbose_name": "adaptação",
                "verbose_name_plural": "adaptações",
                "ordering": ["livro__titulo"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("livro", "content_type", "object_id"),
                        name="livro_nao_repete_a_mesma_adaptacao",
                    )
                ],
            },
        ),
    ]
